version: '3'

services:
  # postgres database
  db-products:
    container_name: db-products
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_products
      POSTGRES_USER: ggutierrez
      POSTGRES_PASSWORD: admin
    ports:
      - '5431:5432'
    expose:
      - '5431'

  db-orders:
    container_name: db-orders
    image: mysql:8.0.33
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ms_orders
      MYSQL_USER: ggutierrez
      MYSQL_PASSWORD: admin
    ports:
      - '3306:3306'
    expose:
      - '3306'

  db-inventory:
    container_name: db-inventory
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_inventory
      POSTGRES_USER: ggutierrez
      POSTGRES_PASSWORD: admin
    ports:
      - '5432:5432'
    expose:
      - '5432'

